# Site settings
title: BusyBox
email: hello@busyboxapp.com
description: > # this means to ignore newlines until "baseurl:"
  BusyBox - Track your time, focus on what matters.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://busyboxapp.com" # the base hostname & protocol for your site
twitter_username: ClaireReynaud

# Build settings
markdown: kramdown
